name: ds

on:
  schedule:
    - cron: '0 9,21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests eventlet

      - name: Run ds
        run: python ${{ github.workspace }}/ds.py
        
      - name: 提交更改
        run: |
          git config --local user.email "wuzhij@mail.com"
          git config --local user.name "wzsvip"
          git add .
          git commit *.txt -m "Add generated file"
          git push -f
